import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const difficulties = {
  easy: { clues: 43, seed: 1103 },
  medium: { clues: 36, seed: 2207 },
  hard: { clues: 31, seed: 3301 },
  expert: { clues: 27, seed: 4409 },
};

const outputPath = resolve("app/data/puzzles.generated.ts");

function makeRng(seed) {
  let state = seed >>> 0;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

function shuffled(values, rng) {
  const result = [...values];
  for (let index = result.length - 1; index > 0; index -= 1) {
    const swap = Math.floor(rng() * (index + 1));
    [result[index], result[swap]] = [result[swap], result[index]];
  }
  return result;
}

function makeSolution(rng) {
  const bandOrder = shuffled([0, 1, 2], rng);
  const stackOrder = shuffled([0, 1, 2], rng);
  const rows = bandOrder.flatMap((band) =>
    shuffled([0, 1, 2], rng).map((row) => band * 3 + row),
  );
  const columns = stackOrder.flatMap((stack) =>
    shuffled([0, 1, 2], rng).map((column) => stack * 3 + column),
  );
  const digits = shuffled([1, 2, 3, 4, 5, 6, 7, 8, 9], rng);
  return rows.flatMap((row) =>
    columns.map((column) => digits[(row * 3 + Math.floor(row / 3) + column) % 9]),
  );
}

function countSolutions(input, limit = 2) {
  const board = [...input];
  const rows = Array(9).fill(0);
  const columns = Array(9).fill(0);
  const boxes = Array(9).fill(0);

  for (let index = 0; index < 81; index += 1) {
    const value = board[index];
    if (!value) continue;
    const row = Math.floor(index / 9);
    const column = index % 9;
    const box = Math.floor(row / 3) * 3 + Math.floor(column / 3);
    const bit = 1 << value;
    if ((rows[row] | columns[column] | boxes[box]) & bit) return 0;
    rows[row] |= bit;
    columns[column] |= bit;
    boxes[box] |= bit;
  }

  let solutions = 0;
  function search() {
    if (solutions >= limit) return;
    let bestIndex = -1;
    let bestMask = 0;
    let bestCount = 10;

    for (let index = 0; index < 81; index += 1) {
      if (board[index]) continue;
      const row = Math.floor(index / 9);
      const column = index % 9;
      const box = Math.floor(row / 3) * 3 + Math.floor(column / 3);
      const mask = 0x3fe & ~(rows[row] | columns[column] | boxes[box]);
      const count = mask.toString(2).replaceAll("0", "").length;
      if (count === 0) return;
      if (count < bestCount) {
        bestIndex = index;
        bestMask = mask;
        bestCount = count;
        if (count === 1) break;
      }
    }

    if (bestIndex === -1) {
      solutions += 1;
      return;
    }

    const row = Math.floor(bestIndex / 9);
    const column = bestIndex % 9;
    const box = Math.floor(row / 3) * 3 + Math.floor(column / 3);
    for (let value = 1; value <= 9; value += 1) {
      const bit = 1 << value;
      if (!(bestMask & bit)) continue;
      board[bestIndex] = value;
      rows[row] |= bit;
      columns[column] |= bit;
      boxes[box] |= bit;
      search();
      board[bestIndex] = 0;
      rows[row] &= ~bit;
      columns[column] &= ~bit;
      boxes[box] &= ~bit;
      if (solutions >= limit) return;
    }
  }

  search();
  return solutions;
}

function digPuzzle(solution, targetClues, rng) {
  const board = [...solution];
  const cells = shuffled(Array.from({ length: 81 }, (_, index) => index), rng);
  for (const index of cells) {
    if (board.filter(Boolean).length <= targetClues) break;
    const previous = board[index];
    board[index] = 0;
    if (countSolutions(board, 2) !== 1) board[index] = previous;
  }
  return board.filter(Boolean).length === targetClues ? board : null;
}

function validatePuzzle(puzzle) {
  if (puzzle.board.length !== 81 || puzzle.solution.length !== 81) return false;
  if (countSolutions(puzzle.board, 2) !== 1) return false;
  return puzzle.board.every(
    (value, index) => value === 0 || value === puzzle.solution[index],
  );
}

const puzzles = [];
for (const [difficulty, config] of Object.entries(difficulties)) {
  const rng = makeRng(config.seed);
  for (let level = 1; level <= 40; level += 1) {
    let board = null;
    let solution = null;
    for (let attempt = 0; attempt < 80 && !board; attempt += 1) {
      solution = makeSolution(rng);
      board = digPuzzle(solution, config.clues, rng);
    }
    if (!board || !solution) {
      throw new Error(`Unable to generate ${difficulty} level ${level}`);
    }
    const puzzle = { id: `${difficulty}-${level}`, difficulty, level, board, solution };
    if (!validatePuzzle(puzzle)) throw new Error(`Invalid puzzle ${puzzle.id}`);
    puzzles.push(puzzle);
  }
}

const file = `// This file is generated by scripts/generate-puzzles.mjs.\n` +
  `import type { Puzzle } from "../lib/types";\n\n` +
  `export const PUZZLES: Puzzle[] = ${JSON.stringify(puzzles)};\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, file, "utf8");
console.log(`Generated and validated ${puzzles.length} fixed puzzles.`);
